name: Build and push Docker image

on:
  push:

jobs:
  buildAndPushImage:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      # Build Docker image
      - id: get-timestamp
        name: Get timestamp
        run: |
          TIMESTAMP=$(date --rfc-3339=seconds | sed 's/ /T/')
          echo "::set-output name=timestamp::$TIMESTAMP"

      - name: Build Docker image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          dockerfile: Dockerfile
          build_extra_args: "--compress=true --label org.opencontainers.image.revision=${{github.sha}} --label org.opencontainers.image.created=${{steps.get-timestamp.outputs.timestamp}}"
          registry: ghcr.io
          stages_image_name: biosimulators/biosimulators_tutorials-stages
          image_name: biosimulators/biosimulators_tutorials-stages
          image_tag: ${{github.sha}}
          push_image_and_stages: true
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: "${{ secrets.DOCKER_REGISTRY_TOKEN }}"

      - name: Label Docker image
        run: |
          docker image tag ghcr.io/biosimulators/biosimulators_tutorials-stages:${{github.sha}} ghcr.io/biosimulators/biosimulators_tutorials:${{github.sha}}
          docker image tag ghcr.io/biosimulators/biosimulators_tutorials-stages:${{github.sha}} ghcr.io/biosimulators/biosimulators_tutorials:latest

      # Test tutorials
      - name: Test tutorials
        run: |
          cwd=$(pwd)
          docker run \
            --rm \
            --entrypoint bash \
            --mount type=bind,source=${cwd},target=/home/Biosimulators_tutorials \
            --workdir /home/Biosimulators_tutorials \
            ghcr.io/biosimulators/biosimulators_tutorials:latest \
            -c "
              pip install nbmake pytest pytest-forked
              /bin/bash /xvfb-startup.sh python -m pytest --forked --verbose --nbmake tutorials/
            "

      # Get version number
      - id: get-version-number
        name: Get version number
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TAG: ${{ github.ref }}
        run: |
          version="${TAG/refs\/tags\//}"
          echo "::set-output name=version::$version"

      # Create GitHub release
      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version-number.outputs.version }}
          release_name: Release ${{ steps.get-version-number.outputs.version }}

      # Push Docker image
      - name: Push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        env:
          VERSION: ${{ steps.get-version-number.outputs.version }}
        run: |
          docker image tag ghcr.io/biosimulators/biosimulators_tutorials:${{github.sha}} ghcr.io/biosimulators/biosimulators_tutorials:${VERSION}

          docker login ghcr.io \
            --username ${{ secrets.DOCKER_REGISTRY_USERNAME }} \
            --password ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          docker push ghcr.io/biosimulators/biosimulators_tutorials:${{github.sha}}
          docker push ghcr.io/biosimulators/biosimulators_tutorials:latest
          docker push ghcr.io/biosimulators/biosimulators_tutorials:${VERSION}
